import { Creator, Post, Conversation, NotificationItem, AnalyticsData, User } from './types';

export const CURRENT_USER: User = {
  id: 'usr_me',
  name: 'Alex Rivera',
  username: 'alex_vip',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  role: 'fan',
  walletBalance: 125.50,
  isVerified: true,
  ghostMode: false,
  watermarkProtection: true,
  e2eeKeyFingerprint: 'E2EE-4491-88FA-992C',
};

export const CREATORS: Creator[] = [
  {
    id: 'creator_1',
    name: 'Elena Rostova',
    username: 'elena_fit',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=1200&auto=format&fit=crop&q=80',
    bio: '✨ Atleta Fitness & Modelo Internacional | Rutinas exclusivas, sesiones privadas y detrás de cámaras diario 🏋️‍♀️🔥 Respuestas a todos los DMs encriptados.',
    category: 'Fitness & Lifestyle',
    isVerified: true,
    subscribersCount: 14820,
    likesCount: 94200,
    postsCount: 248,
    mediaCount: 412,
    subscriptionPrice: 12.99,
    joinedDate: 'Marzo 2023',
    location: 'Madrid / Miami',
    website: 'https://elenafit.vip',
    tiers: [
      {
        id: 'tier_1',
        name: 'Suscripción Mensual',
        price: 12.99,
        period: '1 mes',
        perks: ['Acceso ilimitado al feed completo', 'DMs directos con respuesta rápida', 'Votaciones exclusivas', 'Cifrado E2EE en chat'],
      },
      {
        id: 'tier_2',
        name: 'Pack 3 Meses VIP',
        price: 33.12,
        period: '3 meses',
        discount: 15,
        perks: ['Todo lo del plan mensual', '15% de descuento', '1 set de fotos exclusivo de regalo', 'Insignia VIP en comentarios'],
      },
      {
        id: 'tier_3',
        name: 'Membresía Anual Gold',
        price: 109.11,
        period: '1 año',
        discount: 30,
        perks: ['Acceso total por 1 año', '30% de ahorro', '3 sets PPV desbloqueados gratis', 'Llamada de voz encriptada mensual'],
      },
    ],
  },
  {
    id: 'creator_2',
    name: 'Valentina Santos',
    username: 'valentina_glam',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80',
    bio: '🌴 Modelo de Alta Costura & Viajes | Contenido sin censura y sesiones de fotos en el Caribe 🌊 DMs abiertos para propinas y contenido personalizado.',
    category: 'Glamour & Moda',
    isVerified: true,
    subscribersCount: 28400,
    likesCount: 182000,
    postsCount: 310,
    mediaCount: 560,
    subscriptionPrice: 15.00,
    joinedDate: 'Enero 2022',
    location: 'Ibiza, España',
    tiers: [
      {
        id: 'tier_val_1',
        name: 'Acceso Estándar',
        price: 15.00,
        period: '1 mes',
        perks: ['Acceso al muro principal', 'Sesiones semanales en la playa', 'Chat privado encriptado'],
      },
      {
        id: 'tier_val_2',
        name: 'Pase Trimestral',
        price: 36.00,
        period: '3 meses',
        discount: 20,
        perks: ['Todo lo mensual', 'Set exclusivo de bienvenida', 'Prioridad en solicitudes de video'],
      },
    ],
  },
  {
    id: 'creator_3',
    name: 'Chloe "Kitsune" Moreau',
    username: 'chloe_cosplay',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1511447333015-45b65e60f6d5?w=1200&auto=format&fit=crop&q=80',
    bio: '🦊 Cosplayer Profesional & Artista Digital 🎮 Sets anime temáticos exclusivos, confección de armaduras y streaming privado para fans.',
    category: 'Cosplay & Gaming',
    isVerified: true,
    subscribersCount: 9340,
    likesCount: 65100,
    postsCount: 184,
    mediaCount: 290,
    subscriptionPrice: 9.99,
    joinedDate: 'Mayo 2023',
    location: 'París / Tokio',
    tiers: [
      {
        id: 'tier_chloe_1',
        name: 'Club Otaku',
        price: 9.99,
        period: '1 mes',
        perks: ['Fotos en alta resolución', 'Acceso a tutoriales de cosplay', 'Comentarios destacados'],
      },
    ],
  },
  {
    id: 'creator_4',
    name: 'Marcos Benítez',
    username: 'marcos_chef',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&auto=format&fit=crop&q=80',
    bio: '👨‍🍳 Chef Michelin Privado | Recetas secretas sin censura gastronómica, técnicas de vanguardia y masterclasses privadas semanales 🍷',
    category: 'Gourmet & Cocina',
    isVerified: true,
    subscribersCount: 6720,
    likesCount: 42100,
    postsCount: 140,
    mediaCount: 210,
    subscriptionPrice: 8.50,
    joinedDate: 'Noviembre 2023',
    location: 'Barcelona, España',
    tiers: [
      {
        id: 'tier_marcos_1',
        name: 'Sous Chef Tier',
        price: 8.50,
        period: '1 mes',
        perks: ['Recetario privado descargable', 'Menús degustación exclusivos', 'Consultas gastronómicas por DM'],
      },
    ],
  },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post_1',
    creatorId: 'creator_1',
    creator: {
      name: 'Elena Rostova',
      username: 'elena_fit',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80',
      isVerified: true,
    },
    content: 'Comenzando la semana con toda la energía en el gym 💪 ¿Quién entrena hoy conmigo? Dejadme en los comentarios qué grupo muscular os toca hoy. ¡Más tarde subiré el set completo!',
    mediaUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=900&auto=format&fit=crop&q=80',
    mediaType: 'image',
    isLocked: false,
    createdAt: 'Hace 45 minutos',
    likes: 842,
    commentsCount: 38,
    tipsTotal: 65.00,
    isLikedByMe: true,
    isSubscribedCreator: true,
    moderation: {
      approved: true,
      confidence: 0.98,
      riskLevel: 'LOW',
      moderationTag: 'VERIFIED_SAFE',
      explanation: 'Contenido deportivo y motivacional certificado conforme a directivas comunitarias.',
      verifiedAt: '2026-09-20 18:30',
    },
    comments: [
      {
        id: 'comm_1',
        userId: 'u_101',
        userName: 'Carlos M.',
        userUsername: 'carlos_gym',
        userAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
        text: '¡Esa rutina de pierna es brutal Elena! Saludos desde Colombia 🔥',
        createdAt: 'Hace 20 min',
        likes: 12,
      },
      {
        id: 'comm_2',
        userId: 'u_102',
        userName: 'Lucía Fernández',
        userUsername: 'lucia_fitlife',
        userAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80',
        text: '¡Impresionante definición! Eres mi mayor inspiración.',
        createdAt: 'Hace 10 min',
        likes: 8,
      },
    ],
  },
  {
    id: 'post_2',
    creatorId: 'creator_1',
    creator: {
      name: 'Elena Rostova',
      username: 'elena_fit',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80',
      isVerified: true,
    },
    content: '🔒 EXCLUSIVO VIP: Sesión completa privada de sauna y recuperación post-entreno en Miami Beach. 12 fotos en ultra alta definición + clip exclusivo de 4 minutos 🥵💦',
    mediaUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=900&auto=format&fit=crop&q=80',
    mediaType: 'image',
    isLocked: true,
    unlockPrice: 15.00,
    createdAt: 'Hace 2 horas',
    likes: 1420,
    commentsCount: 92,
    tipsTotal: 280.00,
    isLikedByMe: false,
    isUnlockedByMe: false,
    moderation: {
      approved: true,
      confidence: 0.99,
      riskLevel: 'LOW',
      moderationTag: 'VERIFIED_SAFE',
      explanation: 'Contenido artístico exclusivo verificado para mayores de edad con protección E2EE y DRM.',
      verifiedAt: '2026-09-20 17:15',
    },
    comments: [],
  },
  {
    id: 'post_3',
    creatorId: 'creator_2',
    creator: {
      name: 'Valentina Santos',
      username: 'valentina_glam',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&auto=format&fit=crop&q=80',
      isVerified: true,
    },
    content: 'Atardeceres dorados en las calas de Formentera 🌅 Me encanta esta época del año cuando la brisa del mar te acaricia. ¿Os gusta este bikini?',
    mediaUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=900&auto=format&fit=crop&q=80',
    mediaType: 'image',
    isLocked: false,
    createdAt: 'Hace 4 horas',
    likes: 2190,
    commentsCount: 145,
    tipsTotal: 195.00,
    isLikedByMe: true,
    isSubscribedCreator: false,
    moderation: {
      approved: true,
      confidence: 0.97,
      riskLevel: 'LOW',
      moderationTag: 'VERIFIED_SAFE',
      explanation: 'Fotografía de moda de playa aprobada por moderación automática.',
      verifiedAt: '2026-09-20 15:40',
    },
    comments: [],
  },
  {
    id: 'post_4',
    creatorId: 'creator_2',
    creator: {
      name: 'Valentina Santos',
      username: 'valentina_glam',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&auto=format&fit=crop&q=80',
      isVerified: true,
    },
    content: '💎 SESIÓN PRIVADA DE HOTEL: Todo lo que pasó anoche en la suite presidencial... Las fotos más íntimas que jamás he compartido. Solo para mis suscriptores o desbloqueo directo.',
    mediaUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=900&auto=format&fit=crop&q=80',
    mediaType: 'image',
    isLocked: true,
    unlockPrice: 20.00,
    createdAt: 'Hace 6 horas',
    likes: 3840,
    commentsCount: 230,
    tipsTotal: 520.00,
    isLikedByMe: false,
    isUnlockedByMe: false,
    moderation: {
      approved: true,
      confidence: 0.99,
      riskLevel: 'LOW',
      moderationTag: 'VERIFIED_SAFE',
      explanation: 'Contenido íntimo consensuado para mayores de edad, estrictamente regulado y protegido con DRM dinámico.',
      verifiedAt: '2026-09-20 13:00',
    },
    comments: [],
  },
  {
    id: 'post_5',
    creatorId: 'creator_3',
    creator: {
      name: 'Chloe "Kitsune" Moreau',
      username: 'chloe_cosplay',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
      isVerified: true,
    },
    content: '¡Nuevo cosplay de Ahri Espíritu Floral terminado! Me tomó más de 3 semanas elaborar cada cola a mano con luces de neón 🌸✨ ¿Qué os parece?',
    mediaUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=900&auto=format&fit=crop&q=80',
    mediaType: 'image',
    isLocked: false,
    createdAt: 'Hace 8 horas',
    likes: 1650,
    commentsCount: 88,
    tipsTotal: 85.00,
    isLikedByMe: false,
    moderation: {
      approved: true,
      confidence: 0.99,
      riskLevel: 'LOW',
      moderationTag: 'VERIFIED_SAFE',
      explanation: 'Contenido artístico y cosplay verificado.',
      verifiedAt: '2026-09-20 11:20',
    },
    comments: [],
  },
];

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_1',
    participant: {
      id: 'creator_1',
      name: 'Elena Rostova',
      username: 'elena_fit',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80',
      isVerified: true,
      isOnline: true,
    },
    lastMessage: '🔒 [Mensaje encriptado de extremo a extremo]',
    lastTimestamp: '19:30',
    unreadCount: 1,
    e2eeFingerprint: 'E2EE-7891-AA44-B102',
    messages: [
      {
        id: 'msg_1',
        senderId: 'creator_1',
        receiverId: 'usr_me',
        ciphertext: '7f991b2c4819d44a29ef18',
        plaintext: '¡Hola Alex! Muchas gracias por suscribirte a mi canal VIP 🥰',
        iv: 'a1b2c3d4e5f60718293a',
        algorithm: 'AES-GCM-256',
        timestamp: '19:15',
      },
      {
        id: 'msg_2',
        senderId: 'usr_me',
        receiverId: 'creator_1',
        ciphertext: '88a104fec90091bf',
        plaintext: '¡Hola Elena! Me encantan tus entrenamientos. ¿Cuándo subes la rutina de espalda?',
        iv: 'b2c3d4e5f60718293a4b',
        algorithm: 'AES-GCM-256',
        timestamp: '19:22',
      },
      {
        id: 'msg_3',
        senderId: 'creator_1',
        receiverId: 'usr_me',
        ciphertext: 'cc4011299efda801293a',
        plaintext: '¡La tengo lista para mañana a primera hora! Te he preparado este clip exclusivo de calentamiento solo para ti ❤️',
        iv: 'c3d4e5f60718293a4b5c',
        algorithm: 'AES-GCM-256',
        timestamp: '19:30',
        isLocked: true,
        unlockPrice: 5.00,
        mediaUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&auto=format&fit=crop&q=80',
        isUnlocked: false,
      },
    ],
  },
  {
    id: 'conv_2',
    participant: {
      id: 'creator_2',
      name: 'Valentina Santos',
      username: 'valentina_glam',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&auto=format&fit=crop&q=80',
      isVerified: true,
      isOnline: false,
      lastSeen: 'Hace 1 hora',
    },
    lastMessage: 'Gracias por la propina de $25 amor 😘',
    lastTimestamp: 'Ayer',
    unreadCount: 0,
    e2eeFingerprint: 'E2EE-4491-99CC-881F',
    messages: [
      {
        id: 'msg_val_1',
        senderId: 'usr_me',
        receiverId: 'creator_2',
        ciphertext: '5511aaee8819ff',
        plaintext: '¡Increíble la foto en la playa Valentina!',
        iv: 'd4e5f60718293a4b5c6d',
        algorithm: 'AES-GCM-256',
        timestamp: 'Ayer 15:40',
      },
      {
        id: 'msg_val_2',
        senderId: 'creator_2',
        receiverId: 'usr_me',
        ciphertext: '88ee7721cc091a',
        plaintext: 'Gracias por la propina de $25 amor 😘 ¡Te va a encantar lo que viene el viernes!',
        iv: 'e5f60718293a4b5c6d7e',
        algorithm: 'AES-GCM-256',
        timestamp: 'Ayer 16:10',
      },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    type: 'post',
    title: 'Nueva publicación exclusiva',
    message: '@elena_fit acaba de publicar un nuevo set exclusivo para suscriptores.',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80',
    timestamp: 'Hace 45 min',
    isRead: false,
  },
  {
    id: 'notif_2',
    type: 'tip',
    title: 'Propina recibida',
    message: 'Has recibido una propina de $15.00 de @marcos_fan por tu comentario destacado.',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
    timestamp: 'Hace 2 horas',
    isRead: false,
  },
  {
    id: 'notif_3',
    type: 'message',
    title: 'Nuevo mensaje E2EE encriptado',
    message: '@valentina_glam te envió un mensaje privado cifrado con clave de seguridad.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    timestamp: 'Hace 5 horas',
    isRead: true,
  },
  {
    id: 'notif_4',
    type: 'subscription',
    title: 'Suscripción renovada',
    message: 'Tu suscripción mensual a @elena_fit se ha renovado con éxito ($12.99).',
    timestamp: 'Ayer',
    isRead: true,
  },
  {
    id: 'notif_5',
    type: 'moderation',
    title: 'Cumplimiento normativo IA',
    message: 'Tu última foto ha superado la auditoría automatizada de cumplimiento (Certificado Seguro).',
    timestamp: 'Hace 2 días',
    isRead: true,
  },
];

export const CREATOR_ANALYTICS: AnalyticsData = {
  totalRevenue: 14920.00,
  netEarnings: 11936.00, // 80% payout
  activeSubscribers: 1482,
  totalTips: 3240.00,
  ppvSales: 5410.00,
  chartData: [
    { date: '14 Sep', earnings: 420, views: 3200, subs: 24 },
    { date: '15 Sep', earnings: 510, views: 3800, subs: 31 },
    { date: '16 Sep', earnings: 480, views: 3400, subs: 28 },
    { date: '17 Sep', earnings: 680, views: 4900, subs: 45 },
    { date: '18 Sep', earnings: 820, views: 5700, subs: 52 },
    { date: '19 Sep', earnings: 940, views: 6800, subs: 64 },
    { date: '20 Sep', earnings: 1150, views: 8200, subs: 89 },
  ],
  topFans: [
    {
      name: 'Roberto Gómez',
      username: 'roberto_g',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
      spentTotal: 650.00,
      badge: 'Patrón VIP #1 (Top 0.1%)',
    },
    {
      name: 'Daniel Sánchez',
      username: 'daniel_s',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
      spentTotal: 420.00,
      badge: 'Fan Platino (Top 1%)',
    },
    {
      name: 'Javier Lozano',
      username: 'javi_lozano',
      avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&auto=format&fit=crop&q=80',
      spentTotal: 340.00,
      badge: 'Super Tipper (Top 3%)',
    },
  ],
};

export const initialCurrentUser = CURRENT_USER;
export const initialCreators = CREATORS;
export const initialPosts = INITIAL_POSTS;
export const initialConversations = INITIAL_CONVERSATIONS;
export const initialNotifications = INITIAL_NOTIFICATIONS;
export const initialAnalytics = CREATOR_ANALYTICS;

